name: ai_expense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  moon_design: ^1.1.0
  freezed_annotation: ^2.3.0
  flutter_riverpod: ^2.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^17.0.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^2.3.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
